/*
 * This file is generated by jOOQ.
 */
package com.example.dao.tables.daos;


import com.example.dao.tables.Student;
import com.example.dao.tables.records.StudentRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class StudentDao extends DAOImpl<StudentRecord, com.example.dao.tables.pojos.Student, Integer> {

    /**
     * Create a new StudentDao without any configuration
     */
    public StudentDao() {
        super(Student.STUDENT, com.example.dao.tables.pojos.Student.class);
    }

    /**
     * Create a new StudentDao with an attached configuration
     */
    @Autowired
    public StudentDao(Configuration configuration) {
        super(Student.STUDENT, com.example.dao.tables.pojos.Student.class, configuration);
    }

    @Override
    public Integer getId(com.example.dao.tables.pojos.Student object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Student.STUDENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchById(Integer... values) {
        return fetch(Student.STUDENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.dao.tables.pojos.Student fetchOneById(Integer value) {
        return fetchOne(Student.STUDENT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchByName(String... values) {
        return fetch(Student.STUDENT.NAME, values);
    }

    /**
     * Fetch records that have <code>score BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchRangeOfScore(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Student.STUDENT.SCORE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>score IN (values)</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchByScore(Long... values) {
        return fetch(Student.STUDENT.SCORE, values);
    }

    /**
     * Fetch records that have <code>class BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchRangeOfClass(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.CLASS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>class IN (values)</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchByClass(String... values) {
        return fetch(Student.STUDENT.CLASS, values);
    }

    /**
     * Fetch records that have <code>age BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchRangeOfAge(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Student.STUDENT.AGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<com.example.dao.tables.pojos.Student> fetchByAge(Integer... values) {
        return fetch(Student.STUDENT.AGE, values);
    }
}
